apiVersion: v1
kind: PersistentVolume
metadata:
  name: helloworld-pv2
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  - ReadOnlyMany
  hostPath:
    path: "/Users/alexly/Desktop/test/openshift.local.clusterup/openshift.local.pv/helloworld-pv2"
  persistentVolumeReclaimPolicy: Retain
