apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: helloworlds.hello.world.com
spec:
  group: hello.world.com
  names:
    kind: Helloworld
    listKind: HelloworldList
    plural: helloworlds
    singular: helloworld
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
