apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: helloworld-operator
rules:
- apiGroups:
  - hello.world.com
  resources:
  - '*'
  verbs:
  - '*'
