apiVersion: v1
kind: PersistentVolume
metadata:
  name: helloworld-pv2
  labels:
    type: gp2
spec:
  storageClassName: gp2
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  - ReadOnlyMany
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
