apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "helloworld-pv3"
spec:
  storageClassName: gp2
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "1Gi"
  volumeName: "helloworld-pv3"
